---

- name: "SECTION | 6.1.1.x | Configure systemd-journald service"
  ansible.builtin.import_tasks:
    file: cis_6.1.1.x.yml

- name: "SECTION | 6.1.2.1.x | Configure systemd-journal-remote"
  when: deb12cis_syslog == 'journald'
  ansible.builtin.import_tasks:
    file: cis_6.1.2.1.x.yml

- name: "SECTION | 6.1.4 | Configure Logfiles"
  ansible.builtin.import_tasks:
    file: cis_6.1.4.x.yml

- name: "SECTION | 6.2.1.x | Configure auditd Service"
  ansible.builtin.import_tasks:
    file: cis_6.2.1.x.yml

- name: "SECTION | 6.2.2.x | Configure Data Retention"
  ansible.builtin.import_tasks:
    file: cis_6.2.2.x.yml

- name: "SECTION | 6.2.3.x | Configure auditd Rules"
  ansible.builtin.import_tasks:
    file: cis_6.2.3.x.yml

- name: "SECTION | 6.2.4.x | Configure auditd File Access"
  ansible.builtin.import_tasks:
    file: cis_6.2.4.x.yml

- name: "SECTION | 6.3.x | Configure Integrity Checking"
  ansible.builtin.import_tasks:
    file: cis_6.3.x.yml
